---

- hosts: all
  become: true
  tasks: 

  - name: remove the apache2 package
    apt: 
      name: apache2
      state: absent

  - name: remove the php module for apache
    apt:
      name: libapache2-mod-php
      state: absent
